#!/usr/bin/env bash
# Ping a host 5 times
#!/bin/bash

# Check if no argument was passed
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP 5 times
ping -c 5 "$1"

